---
- name: nginx 설치
  hosts: all
  become: yes

  vars:
    lnx_name: "{{ 'CentOS' if ansible_distribution == 'CentOS'
                   else 'Ubuntu' if ansible_distribution == 'Ubuntu'
                   else 'ETC' }}"

  tasks:
    - name: 변수에 따른 배포판과 작업파일  선택
      include_tasks: "{{ lnx_name }}.yaml"

  handlers:
    - name: restart web
      service:
        name: nginx
        state: restarted
